# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev

pool:
  name: 'Default'  # Nombre del pool donde está tu agente autoalojado
  demands:
    - Agent.OS -equals Windows_NT

variables:
  flutterSdkVersion: 'stable'  # O la versión específica de Flutter que deseas

steps:  
  - task: FlutterInstall@0
    inputs:
      mode: 'auto'
      channel: 'stable'
      version: 'latest'

  - task: FlutterBuild@0
    inputs:
      projectDirectory: '.'
      target: 'apk'
      buildFlavor: 'release'  # Para construir en modo de producción

  - task: CopyFiles@2  # Copia el APK generado a un directorio de salida
    inputs:
      contents: 'build/app/outputs/flutter-apk/app-release.apk'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1  # Publica el APK como artefacto en Azure DevOps
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'apk'
      publishLocation: 'Container'
    displayName: 'Run a multi-line script'
